spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ThrDly2025!Dev3l0pm3ntK3yW1thH1ghS3cur1tyF0rL0calT3st1ngPurp0s3s

# Enhanced logging để debug
logging:
  level:
    com.threadly.gateway: INFO  # ← Show our filter logs
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
